# Generated by Django 3.2.4 on 2021-06-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_article_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(null=True, upload_to='article/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=models.ImageField(null=True, upload_to='article/'),
        ),
    ]
